name: Translate README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Adding README translations
        uses: ikhsan3adi/markdown-translator@master
        with:
          # ISO Language Codes: https://cloud.google.com/translate/docs/languages  
          LANG: |-
            en
            zh-CN
            ja
            ar
            pt
            es
            fr
            vi
            hi
          FILES: |-
            README.md
            docs/api-service.md
            docs/mobile-app.md
            docs/admin-panel.md